# vim: set ft=toml :


min_version = '2026.4.8'


[hooks]
postinstall = [{ task = 'hooks-install' }]


[settings]
experimental = true
lockfile = true
lockfile_platforms = ['linux-arm64', 'linux-x64', 'macos-arm64']


[tasks.hooks-install]
hide = true
run = [{ task = 'hooks-uninstall' }, 'hk install --mise']

[tasks.hooks-uninstall]
env = { GIT_HOOKS_DIR = '.git/hooks' }
hide = true
run = [
  'mkdir -p -- "${GIT_HOOKS_DIR}"',
  'find -- "${GIT_HOOKS_DIR}" -mindepth 1 -delete',
]

[tasks.lint]
alias = 'default'
run = 'hk fix --all'

[tasks.upgrade]
run = ['mise upgrade --local', 'mise lock']


[tools]
hk = 'latest'
pkl = 'latest'
